### ISSUE TITLE
where is the "folia2cpt_corpus.py" file?

### ISSUE THREAD

**Issue by techstone** [NLeSC/cptm#3]
I cannot find this file, could you please tell me where it is ?

![wx20171023-102636](https://user-images.githubusercontent.com/3388926/31867504-bdbadd2c-b7dc-11e7-940b-43d0712e4e92.png)

**Comment by jvdzwaan** [comment]
I'm guessing it is the `folia2cpt_input.py` script. Can you try that?

**Comment by techstone** [comment]
Thanks very much. It works for me now.
